#%RAML 0.8
title: billing
version: v1
#baseUri: http://api.example.com/{version}
#baseUri: http://mocksvc.mulesoft.com/mocks/9a9677ff-a70f-4a4c-a311-6f5750097ed7/{version}
baseUri: http://mocksvc.mulesoft.com/mocks/bd3c6a51-c909-4fb5-8c49-84cc4b823abc/mocks/9a9677ff-a70f-4a4c-a311-6f5750097ed7/{version}
/users/{userId}:
    uriParameters: 
     userId:
      description: the user
    get:
      description: reterive the specific user
      queryParameters:
       showdetails:
        type: boolean
        description: show detail informatioritpn 
      responses:
        200:
         headers: 
         body: 
           application/json:
            example: |
              { "name": "S Arash"
                "email": "sarash@yahoo.com"
              }
        404:
          body:
            application/json:
              example: |
                {"message": "user not found"}

              

       

    
   